### ISSUE TITLE
Hardware video decoding not detected on Ubuntu 20.04.6 with X11 and Intel HD graphics

### ISSUE THREAD

**Issue by cbrenberg** [maxiberta/moonlight-snap#19]
After a year or so without problems, all of a sudden a few days ago the Moonlight snap on my Ubuntu machine with Intel HD integrated graphics starting showing me a warning message about hardware decoding not being detected.

Not sure if the actual issue is related to the snap package, the upstream Moonlight project, or the most recent Ubuntu or kernel updates. I checked the system logs (pasted below), and the lines jumping out at me say "Moonlight not compiled with VAAPI X11 support", then fails to open a VDPAU backend (which maybe isn't even necessary for Intel graphics), before eventually falling back on software decoding via ffmpeg. I see more or less the same info when I run moonlight from a terminal. Hopefully somebody here can provide some insights or point me toward a resolution.

I should also mention that I tried manually installing vainfo and its dependencies to see if it had any effect, and running vainfo correctly shows the current VAAPI version information, but the snap isn't recognizing the system installation of VAAPI.

```
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - SDL Info (0): Loaded 266 new gamepad mappings
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - SDL Info (0): V-sync disabled
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - SDL Error (0): Moonlight not compiled with VAAPI X11 support!
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - SDL Error (0): Moonlight not compiled with VAAPI X11 support!
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - FFmpeg: [AVHWDeviceContext @ 0x7fc1387e1dc0] VDPAU device creation on X11 display :0 failed.
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - SDL Error (0): Failed to create VDPAU context: -1313558101
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - FFmpeg: [AVHWDeviceContext @ 0x7fc13803c080] VDPAU device creation on X11 display :0 failed.
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - SDL Error (0): Failed to create VDPAU context: -1313558101
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - FFmpeg: [AVHWDeviceContext @ 0x7fc138894780] Cannot load libcuda.so.1
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - FFmpeg: [AVHWDeviceContext @ 0x7fc138894780] Could not dynamically load CUDA
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - SDL Error (0): av_hwdevice_ctx_create(CUDA) failed: -1
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - FFmpeg: [AVHWDeviceContext @ 0x7fc138028840] Cannot load libcuda.so.1
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - FFmpeg: [AVHWDeviceContext @ 0x7fc138028840] Could not dynamically load CUDA
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - SDL Error (0): av_hwdevice_ctx_create(CUDA) failed: -1
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - SDL Error (0): Moonlight not compiled with VAAPI X11 support!
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - SDL Error (0): Moonlight not compiled with VAAPI X11 support!
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - FFmpeg: [AVHWDeviceContext @ 0x7fc1387bd380] VDPAU device creation on X11 display :0 failed.
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - SDL Error (0): Failed to create VDPAU context: -1313558101
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - FFmpeg: [AVHWDeviceContext @ 0x7fc13814f900] VDPAU device creation on X11 display :0 failed.
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - SDL Error (0): Failed to create VDPAU context: -1313558101
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - SDL Info (0): Using SDL renderer
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - FFmpeg: [h264 @ 0x7fc1385702c0] nal_unit_type: 7(SPS), nal_ref_idc: 3
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - FFmpeg: [h264 @ 0x7fc1385702c0] nal_unit_type: 8(PPS), nal_ref_idc: 3
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - FFmpeg: [h264 @ 0x7fc1385702c0] nal_unit_type: 5(IDR), nal_ref_idc: 3
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - FFmpeg: [h264 @ 0x7fc1385702c0] nal_unit_type: 5(IDR), nal_ref_idc: 3
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - FFmpeg: [h264 @ 0x7fc1385702c0] nal_unit_type: 5(IDR), nal_ref_idc: 3
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - FFmpeg: [h264 @ 0x7fc1385702c0] nal_unit_type: 5(IDR), nal_ref_idc: 3
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - FFmpeg: [h264 @ 0x7fc1385702c0] Decoding VUI
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - FFmpeg: [h264 @ 0x7fc1385702c0] Format yuv420p chosen by get_format().
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - FFmpeg: [h264 @ 0x7fc1385702c0] Reinit context to 1280x720, pix_fmt: yuv420p
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - SDL Info (0): FFmpeg-based video decoder chosen
Apr 01 16:36:41 server moonlight_moonlight.desktop[3136]: 03:03:25 - SDL Info (0): Encoder configured for 4 slices per frame

**Comment by maxiberta** [comment]
I'll take a closer look and try to reproduce asap. Meanwhile, have you tried `snap revert moonlight`? Are you on `stable`? If so, maybe try switching to the `edge` channel as well.
Thanks!

**Comment by cbrenberg** [comment]
Thanks! I tried the `edge` channel, and still seeing the same warning. 

I unfortunately already removed and reinstalled while troubleshooting, so there's no previous version to revert to. If it comes to it I could try building a previous version from source to try to isolate the problem, but don't know how that works or if it's even possible with snaps without setting up a bunch of extra tooling.

**Comment by ghwatson** [comment]
just chiming in to say i have the same issue on edge channel and stable

similar deal with the VAAPI and it opting for ffmpeg instead

**Comment by ghwatson** [comment]
@cbrenberg if you need a temporary quickfix, install flatpak and moonlight with it

**Comment by Luiszzzor** [comment]
> After a year or so without problems, all of a sudden...

Ye, I was shocked as well ^^. Same problem. When I checked installation folders of snap packages I saw that revision `1984` is missing `/snap/moonlight/1961/usr/lib/libva-x11*` libraries. Previous installed package in my system with revision `1961` has all the libs. Reverting back to `1961` fixed it. I'm sure it must be an oversight and it will be easily fixed in next revision.

**Comment by maxiberta** [comment]
This should now be fixed in all channels. Thanks all!

**Comment by cbrenberg** [comment]
Thanks @maxiberta! Just updated and can confirm this issue is resolved

**Comment by albrechtf** [comment]
Unfortunately, the issue persists on an NVIDIA MX150 Hybrid Card (using Intel HD Graphics for H264 decoding), although the error output of moonlight changed with the latest update:


```
0:00:00 - Qt Warning: Qt: Session management error: Could not open network socket
00:00:00 - SDL Info (0): Compiled with SDL 2.26.0
00:00:00 - SDL Info (0): Running with SDL 2.26.0
00:00:00 - Qt Info: Successfully loaded translation for "de_DE"
00:00:00 - Qt Warning: qrc:/gui/main.qml:12:1: QML ApplicationWindow: ToolTip must be attached to an Item
00:00:00 - Qt Warning: propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.333\" (uid=1000 pid=27104 comm=\"/snap/moonlight/1990/usr/bin/moonlight \" label=\"snap.moonlight.moonlight (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1323 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
00:00:00 - Qt Warning: nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.333\" (uid=1000 pid=27104 comm=\"/snap/moonlight/1990/usr/bin/moonlight \" label=\"snap.moonlight.moonlight (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1323 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
00:00:00 - Qt Warning: "Object path cannot be empty"
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at "/home/florian/snap/moonlight/common/.cache/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 266 new gamepad mappings
00:00:00 - SDL Info (0): V-sync disabled
libva info: VA-API version 1.18.0
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
00:00:00 - SDL Info (0): Trying fallback VAAPI driver names
libva info: VA-API version 1.18.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: VA-API version 1.18.0
libva info: User environment variable requested driver 'i965'
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
libva info: VA-API version 1.18.0
libva info: User environment variable requested driver 'radeonsi'
libva info: Trying to open /usr/lib/dri/radeonsi_drv_video.so
libva info: va_openDriver() returns -1
00:00:00 - SDL Info (0): Trying fallback VAAPI driver paths
libva info: VA-API version 1.18.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Trying to open /usr/lib64/va/drivers/iHD_drv_video.so
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: Trying to open /usr/lib/va/drivers/iHD_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Trying to open /usr/lib64/va/drivers/i965_drv_video.so
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Trying to open /usr/lib/va/drivers/i965_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
00:00:00 - SDL Info (0): Trying fallback VAAPI driver names
libva info: VA-API version 1.18.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Trying to open /usr/lib64/va/drivers/iHD_drv_video.so
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: Trying to open /usr/lib/va/drivers/iHD_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: VA-API version 1.18.0
libva info: User environment variable requested driver 'i965'
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Trying to open /usr/lib64/va/drivers/i965_drv_video.so
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Trying to open /usr/lib/va/drivers/i965_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
libva info: VA-API version 1.18.0
libva info: User environment variable requested driver 'radeonsi'
libva info: Trying to open /usr/lib64/dri/radeonsi_drv_video.so
libva info: Trying to open /usr/lib64/va/drivers/radeonsi_drv_video.so
libva info: Trying to open /usr/lib/dri/radeonsi_drv_video.so
libva info: Trying to open /usr/lib/va/drivers/radeonsi_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: va_openDriver() returns -1
00:00:00 - SDL Error (0): Failed to initialize VAAPI: -1
libva info: VA-API version 1.18.0
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
00:00:00 - SDL Info (0): Trying fallback VAAPI driver names
libva info: VA-API version 1.18.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: VA-API version 1.18.0
libva info: User environment variable requested driver 'i965'
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
libva info: VA-API version 1.18.0
libva info: User environment variable requested driver 'radeonsi'
libva info: Trying to open /usr/lib/dri/radeonsi_drv_video.so
libva info: va_openDriver() returns -1
00:00:00 - SDL Info (0): Trying fallback VAAPI driver paths
libva info: VA-API version 1.18.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Trying to open /usr/lib64/va/drivers/iHD_drv_video.so
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: Trying to open /usr/lib/va/drivers/iHD_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Trying to open /usr/lib64/va/drivers/i965_drv_video.so
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Trying to open /usr/lib/va/drivers/i965_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
00:00:00 - SDL Info (0): Trying fallback VAAPI driver names
libva info: VA-API version 1.18.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Trying to open /usr/lib64/va/drivers/iHD_drv_video.so
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: Trying to open /usr/lib/va/drivers/iHD_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: VA-API version 1.18.0
libva info: User environment variable requested driver 'i965'
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Trying to open /usr/lib64/va/drivers/i965_drv_video.so
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Trying to open /usr/lib/va/drivers/i965_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
libva info: VA-API version 1.18.0
libva info: User environment variable requested driver 'radeonsi'
libva info: Trying to open /usr/lib64/dri/radeonsi_drv_video.so
libva info: Trying to open /usr/lib64/va/drivers/radeonsi_drv_video.so
libva info: Trying to open /usr/lib/dri/radeonsi_drv_video.so
libva info: Trying to open /usr/lib/va/drivers/radeonsi_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: va_openDriver() returns -1
00:00:00 - SDL Error (0): Failed to initialize VAAPI: -1
Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f702c049600] VDPAU device creation on X11 display :1 failed.
00:00:00 - SDL Error (0): Failed to create VDPAU context: -1313558101
Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f702c05a580] VDPAU device creation on X11 display :1 failed.
00:00:00 - SDL Error (0): Failed to create VDPAU context: -1313558101
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f702c04bb40] Loaded lib: libcuda.so.1
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f702c04bb40] Loaded sym: cuInit
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f702c04bb40] Loaded sym: cuDeviceGetCount
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f702c04bb40] Loaded sym: cuDeviceGet
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f702c04bb40] Loaded sym: cuDeviceGetAttribute
[...]
```

Note that I just compiled moonlight-qt 4.3.1 myself, and that works very fine and detects the hardware acceleration. It uses VA API 1.14 instead of 1.18:



```
00:00:00 - SDL Info (0): Compiled with SDL 2.0.20
00:00:00 - SDL Info (0): Running with SDL 2.0.20
00:00:00 - Qt Info: Successfully loaded translation for "de_DE"
00:00:00 - Qt Warning: qrc:/gui/main.qml:12:1: QML ApplicationWindow: ToolTip must be attached to an Item
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at "/home/florian/.cache/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 292 new gamepad mappings
00:00:00 - SDL Info (0): V-sync disabled
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva info: va_openDriver() returns 0
00:00:00 - SDL Info (0): Initialized VAAPI 1.14
00:00:00 - SDL Info (0): Driver: Intel iHD driver for Intel(R) Gen Graphics - 22.3.1 ()
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x41524742 -> bgra.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x42475241 -> argb.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x41424752 -> rgba.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x52474241 -> abgr.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x58524742 -> bgr0.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x42475258 -> 0rgb.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x58424752 -> rgb0.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x52474258 -> 0bgr.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x30335241 -> unknown.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x30334241 -> unknown.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x30335258 -> x2rgb10le.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x30334258 -> unknown.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x36314752 -> unknown.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x50424752 -> unknown.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x50524742 -> unknown.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x56555941 -> unknown.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x30303859 -> gray.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x3231564e -> nv12.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x3132564e -> unknown.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x32595559 -> yuyv422.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x59565955 -> uyvy422.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x32315659 -> yuv420p.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x30323449 -> yuv420p.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x50313134 -> yuv411p.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x48323234 -> yuv422p.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x56323234 -> yuv440p.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x50343434 -> yuv444p.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x33434d49 -> unknown.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Format 0x30313050 -> p010le.
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 22.3.1 ().
00:00:00 - FFmpeg: [AVHWDeviceContext @ 0x7f68cc062b80] Driver not found in known nonstandard list, using standard behaviour.
00:00:00 - SDL Info (0): VAAPI driver supports exporting DRM PRIME surface handles with composed layers
00:00:00 - SDL Info (0): VAAPI driver supports exporting DRM PRIME surface handles with composed layers
00:00:00 - SDL Info (0): Opened DRM render node: /dev/dri/renderD128
00:00:00 - SDL Info (0): Direct rendering via DRM is disabled
00:00:00 - SDL Info (0): VAAPI driver supports exporting DRM PRIME surface handles with separate layers
00:00:00 - SDL Info (0): Color buffer is: R8G8B8A0
00:00:00 - SDL Info (0): EGL passed preflight checks. Using EGL for GL context creation.
00:00:00 - SDL Info (0): Using VAAPI accelerated renderer on x11
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] nal_unit_type: 32(VPS), nuh_layer_id: 0, temporal_id: 0
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] nal_unit_type: 33(SPS), nuh_layer_id: 0, temporal_id: 0
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] nal_unit_type: 34(PPS), nuh_layer_id: 0, temporal_id: 0
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] nal_unit_type: 21(CRA_NUT), nuh_layer_id: 0, temporal_id: 0
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] nal_unit_type: 21(CRA_NUT), nuh_layer_id: 0, temporal_id: 0
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] nal_unit_type: 21(CRA_NUT), nuh_layer_id: 0, temporal_id: 0
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] nal_unit_type: 21(CRA_NUT), nuh_layer_id: 0, temporal_id: 0
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] Decoding VPS
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] Main 10 profile bitstream
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] Decoding SPS
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] Main 10 profile bitstream
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] Decoding VUI
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] Decoding PPS
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] Format vaapi_vld chosen by get_format().
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] Format vaapi_vld requires hwaccel initialisation.
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] Considering format 0x30313050 -> p010le.
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] Picked p010le (0x30313050) as best match for yuv420p10le.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x7f68cc3caa40] Created surface 0.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x7f68cc3caa40] Direct mapping possible.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x7f68cc3caa40] Created surface 0x1.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x7f68cc3caa40] Created surface 0x2.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x7f68cc3caa40] Created surface 0x3.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x7f68cc3caa40] Created surface 0x4.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x7f68cc3caa40] Created surface 0x5.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x7f68cc3caa40] Created surface 0x6.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x7f68cc3caa40] Created surface 0x7.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x7f68cc3caa40] Created surface 0x8.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x7f68cc3caa40] Created surface 0x9.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x7f68cc3caa40] Created surface 0xa.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x7f68cc3caa40] Created surface 0xb.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x7f68cc3caa40] Created surface 0xc.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x7f68cc3caa40] Created surface 0xd.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x7f68cc3caa40] Created surface 0xe.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x7f68cc3caa40] Created surface 0xf.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x7f68cc3caa40] Created surface 0x10.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x7f68cc3caa40] Created surface 0x11.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x7f68cc3caa40] Created surface 0x12.
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x7f68cc3caa40] Created surface 0x13.
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] Considering format 0x30313050 -> p010le.
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] Picked p010le (0x30313050) as best match for yuv420p10le.
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] Decode context initialised: 0x16/0x10000000.
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] Output frame with POC 3.
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] Param buffer (type 0, 604 bytes) is 0.
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] Slice 0 param buffer (264 bytes) is 0x1.
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] Slice 0 data buffer (77 bytes) is 0x2.
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] Slice 1 param buffer (264 bytes) is 0x3.
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] Slice 1 data buffer (87 bytes) is 0x4.
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] Slice 2 param buffer (264 bytes) is 0x5.
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] Slice 2 data buffer (96 bytes) is 0x6.
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] Slice 3 param buffer (264 bytes) is 0x7.
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] Slice 3 data buffer (77 bytes) is 0x8.
00:00:00 - FFmpeg: [hevc @ 0x7f68cc3bd540] Decode to surface 0x13.
00:00:00 - SDL Info (0): FFmpeg-based video decoder chosen
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at "/home/florian/.cache/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 292 new gamepad mappings
00:00:00 - Qt Debug: Current Moonlight version: "4.3.1"
```

I use Ubuntu 22.04 LTS and updated all packages. I even force-reinstalled some of the Intel and VA-API related packages, error unfortunately persists. I am not sure if this is a problem with VA API 1.14 and 1.18, though (maybe binary incompatibility)...

**Comment by albrechtf** [comment]
After the latest update of Ubuntu 22.04 packages, the snap version finally works fine again.
